id = "syscript"
name = "Syscript"
version = "0.0.1"
schema_version = 1
authors = ["Aaron Menadue <aaron.menadue+zedmd@gmail.com>"]
description = "Syscript LSP for the Zed editor."
repository = "https://github.com/IsCoffeeTho/syscript-zed"

[language_servers.syscript]
name = "Syscript LSP"
languages = ["Syscript"]

[grammars.syscript]
repository = "https://github.com/IsCoffeeTho/tree-sitter-syscript"
rev = "666c95d98eff5a1f1d57335b91c7b39041da0766"